### ISSUE TITLE
Kaniko Build Args env variables

### ISSUE THREAD

**Issue by nilpntr** [brendangeck/semantic-release-kaniko#20]
I would like to pass an env variable to `KANIKO_BUILD_ARG` like this:
```yaml
  variables:
    DOCKER_REGISTRY: "${CI_REGISTRY}"
    DOCKER_USERNAME: "gitlab-ci-token"
    DOCKER_PASSWORD: "${CI_JOB_TOKEN}"
    KANIKO_DESTINATION: >-
      ["${CI_REGISTRY_IMAGE}:$${version}"]
    KANIKO_BUILD_ARG: '[{"name": "VERSION", "value": "$${version}"}]'
    KANIKO_CACHE: true
    KANIKO_CACHE_TTL: "48h"
    KANIKO_KANIKO_DIR: /tmp/kaniko
    KANIKO_CONTEXT: ${CI_PROJECT_DIR}
```

Is it possible to set for example `${nextRelease.version}` or `$${version}` used in KANIKO_DESTINATION?
